
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sabrina
 */
public class BukuForm extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form BukuForm
     */
    String[] headerNames = {"Genre", "Judul", "Penulis", "Penerbit", "Tahun", "Harga", "Stok"};
    DefaultTableModel model = new DefaultTableModel(null, headerNames);
    public BukuForm(ResultSet res, boolean is_all) {
        config DB = new config();
        DB.connection();
        con = DB.con;
        stat = DB.stm;
        initComponents();
        if(is_all == false){
            try {
                sql = "SELECT * FROM buku WHERE id_genre='"+res.getString("id")+"'";
                rs = stat.executeQuery(sql);
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
            }    
        }else{
            try {
                sql = "SELECT * FROM buku";
                rs = stat.executeQuery(sql);
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
            }    
        }
        
        try {
            while(rs.next()){
                try {
                    model.addRow(new Object[]{
                        res.getString("nama_genre"),rs.getString("judul"), rs.getString("penulis"), rs.getString("penerbit"), rs.getString("tahun"), rs.getString("harga"), rs.getString("stok")
                    });
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                if(is_all==true){
                    try {
                        res.next();
                    } catch (SQLException ex) {
                        Logger.getLogger(BukuForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BukuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    GenreForm wel = new GenreForm();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btn_cart = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilih Buku Form");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabel);

        btn_cart.setText("Add to Cart");
        btn_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cartActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
            .addComponent(btn_cart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cartActionPerformed
        try {
            int baris = tabel.getSelectedRow();
            int countBuku = 0;
            while(wel.getId_buku()[countBuku]!=null){
                countBuku++;
            }
            sql = "SELECT * FROM buku WHERE judul='"+tabel.getValueAt(baris, 1)+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                wel.setId_buku(rs.getString("id"), countBuku);
                wel.setTotal_cart(wel.getTotal_cart() + Integer.parseInt(rs.getString("harga"));
                showDetail();
            }
        } catch (SQLException ex) {
            Logger.getLogger(BukuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_cartActionPerformed

    public void showDetail(){
        String cartString = "";
//        int countBuku = 0;
//        while(wel.id_buku[countBuku]!=null){
//            sql = "SELECT * FROM buku WHERE id='1'";
//            rs = stat.executeQuery(sql);
//            try {
//                if(rs.next()){
//                    cartString = cartString + rs.getString("judul") + " -> " + rs.getString("harga") + "\n";
//                }
//            } catch (SQLException ex) {
//                Logger.getLogger(BukuForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            countBuku++;
//        }
        System.out.println(wel.getTotal_cart());
        JOptionPane.showMessageDialog(null, "Buku sudah ditambahkan ke Cart. \nCart anda : "+ cartString +" \nTotal Harga : Rp."+String.valueOf(wel.getTotal_cart()));
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GenreForm genre = new GenreForm();
        genre.setLocationRelativeTo(null);
        genre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cart;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
