/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GenreForm extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form GenreForm
     */
    public GenreForm() {
        initComponents();
        config DB = new config();
        DB.connection();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_horror = new javax.swing.JButton();
        btn_fantasi = new javax.swing.JButton();
        btn_scifi = new javax.swing.JButton();
        btn_romance = new javax.swing.JButton();
        btn_all = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genre Form");

        jLabel1.setText("Pilih Genre Yang Anda Minati");

        btn_horror.setText("Horror");
        btn_horror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_horrorActionPerformed(evt);
            }
        });

        btn_fantasi.setText("Fantasi");
        btn_fantasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fantasiActionPerformed(evt);
            }
        });

        btn_scifi.setText("Sci-Fi");
        btn_scifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scifiActionPerformed(evt);
            }
        });

        btn_romance.setText("Romance");
        btn_romance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_romanceActionPerformed(evt);
            }
        });

        btn_all.setText("All");
        btn_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_horror)
                    .addComponent(btn_fantasi)
                    .addComponent(btn_scifi)
                    .addComponent(btn_romance)
                    .addComponent(btn_all))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_horror)
                .addGap(18, 18, 18)
                .addComponent(btn_fantasi)
                .addGap(18, 18, 18)
                .addComponent(btn_scifi)
                .addGap(18, 18, 18)
                .addComponent(btn_romance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_all)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean is_all=false;
    private void btn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allActionPerformed
        sql = "SELECT * FROM genre";
        is_all=true;
        try {
            rs = stat.executeQuery(sql);
            this.moveForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btn_allActionPerformed

    private void btn_horrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_horrorActionPerformed
        sql = "SELECT * FROM genre WHERE nama_genre='Horor'";
        try {
            rs = stat.executeQuery(sql);
            this.moveForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btn_horrorActionPerformed

    private void btn_fantasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fantasiActionPerformed
         sql = "SELECT * FROM genre WHERE nama_genre='Fantasi'";
        try {
            rs = stat.executeQuery(sql);
            this.moveForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btn_fantasiActionPerformed

    private void btn_scifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scifiActionPerformed
         sql = "SELECT * FROM genre WHERE nama_genre='Sci-Fi'";
        try {
            rs = stat.executeQuery(sql);
            this.moveForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btn_scifiActionPerformed

    private void btn_romanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_romanceActionPerformed
        sql = "SELECT * FROM genre WHERE nama_genre='Romance'";
        try {
            rs = stat.executeQuery(sql);
            this.moveForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btn_romanceActionPerformed

    
    public void moveForm(){
        try {
            if(rs.next()){
                String id = null;
                try {
                    id = rs.getString("id");
                } catch (SQLException ex) {
                    Logger.getLogger(GenreForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                String genre = null;
                try {
                    genre = rs.getString("nama_genre");
                } catch (SQLException ex) {
                    Logger.getLogger(GenreForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                BukuForm buku = new BukuForm(rs, is_all);
                buku.setLocationRelativeTo(null);
                buku.setVisible(true);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GenreForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_all;
    private javax.swing.JButton btn_fantasi;
    private javax.swing.JButton btn_horror;
    private javax.swing.JButton btn_romance;
    private javax.swing.JButton btn_scifi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
